#!/bin/bash -e

NAME=$1

if [ -z "$NAME" ]; then
    echo "Usage: $0 PACKAGE_NAME"
    exit 1
fi

cd "$HOME/rpmbuild/package"

mkdir -p target
rm -f target/$NAME-*.src.rpm

spectool -g -R $NAME.spec
rpmbuild -bs --nodeps $NAME.spec
yum-builddep -y $NAME.spec
rpmbuild --rebuild target/$NAME-*.src.rpm
