#!/bin/bash -e

NAME=$1
MACROSFILE=/root/.rpmmacros

readmacro() {
    local NAME="$1"
    awk '{if ($1 == "%'$NAME'") {for (i=2; i<NF; i++) printf $i " "; print $NF}}' "$MACROSFILE"
}

if [ -z "$NAME" ]; then
    echo "Usage: $0 PACKAGE_NAME"
    exit 1
fi

if [ -z "$YUM_CACHE_DIR" ]; then
    YUM_CACHE_DIR='/var/cache/yum/$basearch/$releasever'
else
    mkdir -p "$YUM_CACHE_DIR"
fi

for RPMVAR in TOPDIR SPECDIR SOURCEDIR SRCRPMDIR RPMDIR; do
    VALUE="${!RPMVAR}"
    [ -z "$VALUE" ] && continue
    RPMVAR=${RPMVAR,,} # lowercase
    sed "/^%_$RPMVAR /d" -i "$MACROSFILE"
    echo "%_$RPMVAR $VALUE" >> "$MACROSFILE"
done

if [ ! -z "$MAILTO" ]; then
    sed "/^%_gpg_name /d" -i "$MACROSFILE"
    echo "%_gpg_name $MAILTO" >> "$MACROSFILE"
fi

sed -r "s:^cachedir=.*:cachedir=${YUM_CACHE_DIR}/\$basearch/\$releasever:" -i "$MACROSFILE"

SRCRPMDIR=$(readmacro _srcrpmdir)
SPECDIR=$(readmacro _specdir)

cd "$SPECDIR"

spectool -g -R "$NAME.spec"
yum-builddep -y "$NAME.spec"
/usr/bin/rpmbuild -bs "$NAME.spec"
/usr/bin/rpmbuild --rebuild "$SRCRPMDIR/$NAME"-*.src.rpm
